import { Kysely, sql } from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
  await db.schema
    .createTable('oauthClient')
    .ifNotExists()
    .addColumn('id', 'uuid', (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('clientId', 'text', (col) => col.notNull())
    .addColumn('clientSecret', 'text')
    .addColumn('disabled', 'boolean', (col) => col.notNull().defaultTo(false))
    .addColumn('skipConsent', 'boolean')
    .addColumn('enableEndSession', 'boolean')
    .addColumn('scopes', 'jsonb')
    .addColumn('userId', 'uuid', (col) => col.references('user.id'))
    .addColumn('referenceId', 'text')
    .addColumn('projectId', 'uuid', (col) => col.references('project.id'))
    .addColumn('name', 'text')
    .addColumn('uri', 'text')
    .addColumn('icon', 'text')
    .addColumn('contacts', 'jsonb')
    .addColumn('tos', 'text')
    .addColumn('policy', 'text')
    .addColumn('softwareId', 'text')
    .addColumn('softwareVersion', 'text')
    .addColumn('softwareStatement', 'text')
    .addColumn('redirectUris', 'jsonb', (col) => col.notNull())
    .addColumn('postLogoutRedirectUris', 'jsonb')
    .addColumn('tokenEndpointAuthMethod', 'text')
    .addColumn('grantTypes', 'jsonb')
    .addColumn('responseTypes', 'jsonb')
    .addColumn('public', 'boolean')
    .addColumn('type', 'text')
    .addColumn('metadata', 'jsonb')
    .addColumn('createdAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('updatedAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .execute()

  await db.schema
    .createIndex('oauthClient_clientId_uq')
    .ifNotExists()
    .on('oauthClient')
    .column('clientId')
    .unique()
    .execute()

  await db.schema
    .createIndex('oauthClient_projectId_uq')
    .ifNotExists()
    .on('oauthClient')
    .column('projectId')
    .unique()
    .execute()

  await db.schema
    .createTable('oauthRefreshToken')
    .ifNotExists()
    .addColumn('id', 'uuid', (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('token', 'text', (col) => col.notNull())
    .addColumn('clientId', 'text', (col) => col.notNull().references('oauthClient.clientId'))
    .addColumn('sessionId', 'uuid', (col) => col.references('session.id').onDelete('set null'))
    .addColumn('userId', 'uuid', (col) => col.notNull().references('user.id'))
    .addColumn('referenceId', 'text')
    .addColumn('scopes', 'jsonb', (col) => col.notNull())
    .addColumn('createdAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('expiresAt', 'timestamptz', (col) => col.notNull())
    .addColumn('revoked', 'timestamptz')
    .execute()

  await db.schema
    .createTable('oauthAccessToken')
    .ifNotExists()
    .addColumn('id', 'uuid', (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('token', 'text', (col) => col.notNull())
    .addColumn('clientId', 'text', (col) => col.notNull().references('oauthClient.clientId'))
    .addColumn('sessionId', 'uuid', (col) => col.references('session.id').onDelete('set null'))
    .addColumn('userId', 'uuid', (col) => col.references('user.id'))
    .addColumn('referenceId', 'text')
    .addColumn('refreshId', 'uuid', (col) => col.references('oauthRefreshToken.id'))
    .addColumn('scopes', 'jsonb', (col) => col.notNull())
    .addColumn('createdAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('expiresAt', 'timestamptz', (col) => col.notNull())
    .execute()

  await db.schema
    .createIndex('oauthAccessToken_token_uq')
    .ifNotExists()
    .on('oauthAccessToken')
    .column('token')
    .unique()
    .execute()

  await db.schema
    .createTable('oauthConsent')
    .ifNotExists()
    .addColumn('id', 'uuid', (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('clientId', 'text', (col) => col.notNull().references('oauthClient.clientId'))
    .addColumn('userId', 'uuid', (col) => col.references('user.id'))
    .addColumn('referenceId', 'text')
    .addColumn('scopes', 'jsonb', (col) => col.notNull())
    .addColumn('createdAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('updatedAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .execute()

  await db.schema
    .createTable('jwks')
    .ifNotExists()
    .addColumn('id', 'uuid', (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('publicKey', 'text', (col) => col.notNull())
    .addColumn('privateKey', 'text', (col) => col.notNull())
    .addColumn('createdAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('expiresAt', 'timestamptz')
    .execute()
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.dropTable('jwks').ifExists().execute()
  await db.schema.dropTable('oauthConsent').ifExists().execute()
  await db.schema.dropTable('oauthAccessToken').ifExists().execute()
  await db.schema.dropTable('oauthRefreshToken').ifExists().execute()
  await db.schema.dropTable('oauthClient').ifExists().execute()
}
