include "base.conf"

queues {
  webhooks {
    defaultVisibilityTimeout = 30
    delay = 0
    receiveMessageWait = 0
    deadLettersQueue {
      name = "webhooks_dlq"
      maxReceiveCount = 3
    }
  }

  webhooks_dlq {
    defaultVisibilityTimeout = 30
    delay = 0
    receiveMessageWait = 0
  }
}

rest-sqs {
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  enabled = true
  sqs-limits = strict
}
