include classpath("application.conf")

pekko.http.parsing {
  illegal-header-warnings = off
  ignore-illegal-header-for = ["user-agent", "authorization"]
}

queues {
  webhooks {
    defaultVisibilityTimeout = 30 seconds
    delay = 0 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "webhooks_dlq"
      maxReceiveCount = 3
    }
  }

  webhooks_dlq {
    defaultVisibilityTimeout = 30 seconds
    delay = 0 seconds
    receiveMessageWait = 20 seconds
  }
}

rest-sqs {
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  enabled = true
  sqs-limits = strict
}
