export { EditorState } from '@codemirror/state'
export type { Extension } from '@codemirror/state'
export { EditorView } from '@codemirror/view'
export { unifiedMergeView, presentableDiff } from '@codemirror/merge'
export { javascript } from '@codemirror/lang-javascript'
export { python } from '@codemirror/lang-python'
export { css } from '@codemirror/lang-css'
export { html } from '@codemirror/lang-html'
export { json } from '@codemirror/lang-json'
export { markdown } from '@codemirror/lang-markdown'
export { syntaxHighlighting, defaultHighlightStyle } from '@codemirror/language'
