ALTER TABLE "website"
  DROP COLUMN IF EXISTS "user_id",
  DROP COLUMN IF EXISTS "team_id",
  DROP COLUMN IF EXISTS "created_by";

ALTER TABLE "report"
  DROP COLUMN IF EXISTS "user_id";

ALTER TABLE "link"
  DROP COLUMN IF EXISTS "user_id",
  DROP COLUMN IF EXISTS "team_id";

ALTER TABLE "pixel"
  DROP COLUMN IF EXISTS "user_id",
  DROP COLUMN IF EXISTS "team_id";

DROP TABLE IF EXISTS "team_user" CASCADE;
DROP TABLE IF EXISTS "team" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
